// Package dnsintel provides DNS-based threat detection algorithms.
// All detectors are non-ML, stateless per-query, and designed to run
// within the event ingest pipeline on Pi 4 hardware (<50MB memory).
package dnsintel

import (
	"math"
	"strings"
	"unicode"
)

// DGAResult holds the output of the DGA scoring algorithm.
type DGAResult struct {
	Score       float64 // 0.0 (benign) to 1.0 (highly suspicious)
	Entropy     float64 // Shannon entropy of the effective domain label
	BigramScore float64 // Bigram frequency anomaly (0.0 = normal, 1.0 = fully random)
	Label       string  // The domain label that was scored
	IsDGA       bool    // True if composite score exceeds threshold
}

// DGAThreshold is the composite score above which a domain is flagged.
const DGAThreshold = 0.65

// ScoreDGA evaluates whether a domain name is likely generated by a
// Domain Generation Algorithm. It combines Shannon entropy analysis with
// character bigram frequency to catch DGA domains that use dictionary
// words to artificially lower entropy.
//
// The effective label is the longest non-TLD label in the domain name.
// For example, "asdfjkl.evil.com" scores "asdfjkl".
func ScoreDGA(domain string) DGAResult {
	domain = strings.TrimSuffix(strings.ToLower(strings.TrimSpace(domain)), ".")

	label := effectiveLabel(domain)
	if label == "" || len(label) < 4 {
		return DGAResult{Label: label}
	}

	entropy := shannonEntropy(label)
	bigram := bigramAnomalyScore(label)

	// Composite: weighted average. Entropy is primary signal, bigram catches
	// dictionary-word DGAs with low entropy but unusual letter pairs.
	composite := 0.6*normalizeEntropy(entropy, len(label)) + 0.4*bigram

	return DGAResult{
		Score:       clamp(composite),
		Entropy:     entropy,
		BigramScore: bigram,
		Label:       label,
		IsDGA:       composite >= DGAThreshold,
	}
}

// effectiveLabel returns the longest non-TLD label in the domain.
// For "long-random-string.co.uk" it returns "long-random-string".
// For "sub.domain.com" it returns whichever of "sub" or "domain" is longer.
func effectiveLabel(domain string) string {
	parts := strings.Split(domain, ".")
	if len(parts) < 2 {
		return domain
	}

	// Remove known multi-part TLDs
	tldParts := 1
	if len(parts) >= 3 {
		possibleTLD := parts[len(parts)-2] + "." + parts[len(parts)-1]
		if isMultiPartTLD(possibleTLD) {
			tldParts = 2
		}
	}

	labels := parts[:len(parts)-tldParts]
	if len(labels) == 0 {
		return ""
	}

	// Return the longest label (most likely to be the DGA-generated part)
	longest := labels[0]
	for _, l := range labels[1:] {
		if len(l) > len(longest) {
			longest = l
		}
	}
	return longest
}

// shannonEntropy calculates the Shannon entropy (bits per character) of a string.
func shannonEntropy(s string) float64 {
	if len(s) == 0 {
		return 0
	}

	freq := make(map[rune]int)
	for _, c := range s {
		freq[c]++
	}

	length := float64(len(s))
	entropy := 0.0
	for _, count := range freq {
		p := float64(count) / length
		if p > 0 {
			entropy -= p * math.Log2(p)
		}
	}
	return entropy
}

// normalizeEntropy maps raw entropy to a 0–1 suspicion scale.
// Entropy thresholds calibrated from research:
//   - Benign domains: avg entropy ~2.5–3.2
//   - DGA domains: avg entropy ~3.5–4.0+
//   - Max possible for 36-char alphabet (a-z + 0-9): ~5.17
func normalizeEntropy(entropy float64, labelLen int) float64 {
	// Short labels get a bonus (fewer chars = lower max entropy)
	if labelLen < 6 {
		return 0
	}

	// Scale: <3.0 = safe, 3.0–3.5 = mild, 3.5–4.0 = suspicious, >4.0 = very suspicious
	if entropy < 3.0 {
		return 0
	}
	if entropy > 4.2 {
		return 1.0
	}
	return (entropy - 3.0) / 1.2
}

// bigramAnomalyScore measures how unusual the character pairs in a label are
// compared to English text. Returns 0.0 (normal) to 1.0 (very unusual).
//
// Uses a simplified approach: count the fraction of bigrams that are
// consonant-consonant (cc) or contain digits. Normal English has ~15% cc
// bigrams; DGA domains typically have 40–60%+.
func bigramAnomalyScore(s string) float64 {
	if len(s) < 2 {
		return 0
	}

	runes := []rune(s)
	totalBigrams := len(runes) - 1
	if totalBigrams == 0 {
		return 0
	}

	unusual := 0
	for i := 0; i < totalBigrams; i++ {
		a, b := runes[i], runes[i+1]

		// Digit in bigram is unusual for domain labels
		if unicode.IsDigit(a) || unicode.IsDigit(b) {
			unusual++
			continue
		}

		// Consonant-consonant pairs (excluding common ones)
		if isConsonant(a) && isConsonant(b) {
			pair := string([]rune{a, b})
			if !isCommonConsonantPair(pair) {
				unusual++
			}
		}
	}

	ratio := float64(unusual) / float64(totalBigrams)

	// Normal English: ~15% unusual bigrams
	// DGA: ~45%+ unusual bigrams
	if ratio < 0.15 {
		return 0
	}
	if ratio > 0.55 {
		return 1.0
	}
	return (ratio - 0.15) / 0.40
}

var vowels = map[rune]bool{'a': true, 'e': true, 'i': true, 'o': true, 'u': true}

func isConsonant(r rune) bool {
	return r >= 'a' && r <= 'z' && !vowels[r]
}

// Common consonant pairs in English words.
var commonCC = map[string]bool{
	"th": true, "ch": true, "sh": true, "ph": true, "wh": true,
	"ck": true, "nd": true, "ng": true, "nk": true, "nt": true,
	"st": true, "sk": true, "sp": true, "sc": true, "sm": true,
	"sn": true, "sl": true, "sw": true, "str": true, "bl": true,
	"br": true, "cl": true, "cr": true, "dr": true, "fl": true,
	"fr": true, "gl": true, "gr": true, "pl": true, "pr": true,
	"tr": true, "tw": true, "wr": true, "gh": true, "gn": true,
	"kn": true, "mn": true, "ps": true, "rn": true, "rs": true,
	"rt": true, "rd": true, "rl": true, "rm": true, "rk": true,
	"rp": true, "rb": true, "rc": true, "rg": true, "rv": true,
	"lk": true, "lm": true, "ln": true, "lp": true, "lt": true,
	"ld": true, "lf": true, "lv": true, "ls": true, "ft": true,
	"mp": true, "mb": true, "ct": true, "pt": true, "xt": true,
}

func isCommonConsonantPair(pair string) bool {
	return commonCC[pair]
}

// isMultiPartTLD checks for common multi-part TLDs.
var multiPartTLDs = map[string]bool{
	"co.uk": true, "co.jp": true, "co.kr": true, "co.nz": true,
	"co.za": true, "co.in": true, "com.au": true, "com.br": true,
	"com.cn": true, "com.mx": true, "com.tr": true, "com.sg": true,
	"org.uk": true, "net.au": true, "ac.uk": true, "gov.uk": true,
	"edu.au": true, "or.jp": true, "ne.jp": true, "ac.jp": true,
}

func isMultiPartTLD(tld string) bool {
	return multiPartTLDs[tld]
}

func clamp(v float64) float64 {
	if v < 0 {
		return 0
	}
	if v > 1 {
		return 1
	}
	return v
}
