#!/usr/bin/env bash
# gen-env.sh — one-command machine-credential setup for a fresh Vedetta node
# (issue #34). Generates a ready-to-run .env from .env.example with DISTINCT
# strong random secrets, so Quick Start doesn't ship a Core with empty/identical
# tokens that 403 the collector and telemetry daemon.
#
# It writes three secrets that a fresh node otherwise has no safe value for:
#   VEDETTA_INGEST_TOKEN  — collector ingest auth (ingest scope)
#   VEDETTA_CORE_TOKEN    — telemetry read auth   (read scope)   [!= ingest token]
#   VEDETTA_SETUP_CODE    — single-use first-admin bootstrap code
#
# Usage:
#   ./scripts/gen-env.sh            # writes ./.env at the repo root
#   ENV_FILE=/path/to.env ./scripts/gen-env.sh
#
# Refuses to overwrite an existing .env — rotating live credentials is a
# deliberate act, not a side effect of re-running setup. Remove the file (or
# point ENV_FILE elsewhere) to regenerate.

set -euo pipefail

# Resolve the repo root from this script's location so the command works no
# matter the caller's cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

EXAMPLE_FILE="${REPO_ROOT}/.env.example"
ENV_FILE="${ENV_FILE:-${REPO_ROOT}/.env}"

if [[ ! -f "${EXAMPLE_FILE}" ]]; then
  echo "error: ${EXAMPLE_FILE} not found — run from a Vedetta checkout" >&2
  exit 1
fi

if [[ -e "${ENV_FILE}" ]]; then
  echo "error: ${ENV_FILE} already exists — refusing to overwrite." >&2
  echo "       Delete it first if you really want to regenerate credentials." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "error: openssl is required to generate secrets but was not found in PATH" >&2
  exit 1
fi

# Generate two DISTINCT ingest/read secrets. They are matched by scope on the
# Core side, and setting them equal collapses to a single scope (the other
# client then gets 403), so guarantee inequality even in the astronomically
# unlikely collision case.
INGEST_TOKEN="$(openssl rand -hex 32)"
CORE_TOKEN="$(openssl rand -hex 32)"
while [[ "${CORE_TOKEN}" == "${INGEST_TOKEN}" ]]; do
  CORE_TOKEN="$(openssl rand -hex 32)"
done

# The setup code is presented in an HTTP header during bootstrap; keep it
# shell/URL-safe by using hex.
SETUP_CODE="$(openssl rand -hex 16)"

# Write atomically: build into a temp file, then move into place so a failure
# never leaves a half-written .env behind.
UMASK_OLD="$(umask)"
umask 077 # secrets — owner-only from the moment the file exists
TMP_FILE="$(mktemp "${ENV_FILE}.XXXXXX")"
umask "${UMASK_OLD}"
trap 'rm -f "${TMP_FILE}"' EXIT

# Start from the documented template so every non-secret default and comment is
# preserved, then substitute the secret values.
cp "${EXAMPLE_FILE}" "${TMP_FILE}"

# Replace VEDETTA_INGEST_TOKEN= / VEDETTA_CORE_TOKEN= assignment lines in place.
# Values are pure hex, so there are no sed-metacharacter concerns.
set_var() {
  local key="$1" value="$2" file="$3"
  if grep -qE "^${key}=" "${file}"; then
    # Replace the existing assignment line (portable BSD/GNU sed: no -i shared flag).
    sed "s|^${key}=.*|${key}=${value}|" "${file}" >"${file}.tmp" && mv "${file}.tmp" "${file}"
  else
    printf '%s=%s\n' "${key}" "${value}" >>"${file}"
  fi
}

set_var "VEDETTA_INGEST_TOKEN" "${INGEST_TOKEN}" "${TMP_FILE}"
set_var "VEDETTA_CORE_TOKEN" "${CORE_TOKEN}" "${TMP_FILE}"

# .env.example has no VEDETTA_SETUP_CODE line; set_var appends it (with a short
# explanatory comment the first time) so the generated .env documents itself.
if ! grep -qE '^VEDETTA_SETUP_CODE=' "${TMP_FILE}"; then
  {
    printf '\n'
    printf '# Single-use first-admin bootstrap code (generated by scripts/gen-env.sh).\n'
    printf '# Present it in the X-Vedetta-Setup-Code header to mint the first admin token.\n'
  } >>"${TMP_FILE}"
fi
set_var "VEDETTA_SETUP_CODE" "${SETUP_CODE}" "${TMP_FILE}"

mv "${TMP_FILE}" "${ENV_FILE}"
chmod 600 "${ENV_FILE}" # secrets — owner read/write only
trap - EXIT

echo "Wrote ${ENV_FILE} with fresh, distinct machine credentials:"
echo "  VEDETTA_INGEST_TOKEN  (ingest scope)"
echo "  VEDETTA_CORE_TOKEN    (read scope, distinct from ingest)"
echo "  VEDETTA_SETUP_CODE    (single-use first-admin bootstrap)"
echo
echo "Keep this file private (it is gitignored). First admin bootstrap code:"
echo "  ${SETUP_CODE}"
