-- VED-013: Relax the restrictive segment CHECK constraints on devices/events.
--
-- 001_init.sql pins:
--   devices.segment        TEXT ... CHECK (segment IN ('default','iot','guest'))
--   events.network_segment TEXT ... CHECK (network_segment IN ('default','iot','guest'))
-- UniFi ingestion and multi-network correlation now legitimately write other
-- segment names (e.g. 'lan', VLAN names), which the CHECK rejects on the real
-- migration path (tests miss it because the inline-fallback schema in db.go has
-- no CHECK). SQLite cannot drop a CHECK in place, so both tables are rebuilt
-- without the segment CHECK. The segment/network_segment column and its
-- DEFAULT 'default' are preserved; every OTHER CHECK (events.query_type,
-- events.event_type), the PRIMARY KEYs, and all indexes are preserved.
--
-- This migration is authoritative for the final events/devices shape. It uses
-- EXPLICIT column lists in both the CREATE and the copy so it is robust to the
-- fresh-vs-legacy column divergence:
--   * events: a fresh migrated DB has the 19 columns from 001_init.sql (011's
--     ADD threat_desc was swallowed as a no-op because 001-final already carries
--     source_ip/metadata); a legacy incrementally-migrated DB additionally has
--     threat_desc (added by 011 when events still had the 14-col shape). The new
--     events table declares threat_desc so BOTH paths converge on the same shape
--     (it also makes InsertEvents' threat_desc write valid on fresh DBs). The
--     copy references only the columns guaranteed present on both paths; on a
--     legacy DB any prior threat_desc text is regenerated by the enricher.
--   * devices: fresh and legacy converge on the same 25 columns already, so its
--     rebuild is a straightforward explicit-column copy minus the segment CHECK.

PRAGMA foreign_keys = OFF;

-- ── events ────────────────────────────────────────────────────────────────────
ALTER TABLE events RENAME TO events_old_019;

CREATE TABLE events (
    event_id       TEXT PRIMARY KEY,
    timestamp      TIMESTAMP NOT NULL,
    event_type     TEXT NOT NULL CHECK (event_type IN ('dns_query', 'encrypted_dns_detected', 'nmap_discovery', 'firewall_log', 'anomaly')),
    source_hash    TEXT NOT NULL,
    source_ip      TEXT,
    server_ip      TEXT DEFAULT '',
    domain         TEXT,
    query_type     TEXT CHECK (query_type IN ('A', 'AAAA', 'MX', 'TXT', 'CNAME', 'SRV', 'PTR', NULL)),
    resolved_ip    TEXT,
    blocked        BOOLEAN NOT NULL DEFAULT FALSE,
    anomaly_score  REAL NOT NULL DEFAULT 0.0,
    tags           TEXT DEFAULT '[]',
    geo            TEXT,
    device_vendor  TEXT,
    network_segment TEXT DEFAULT 'default',   -- segment CHECK dropped (VED-013)
    dns_source     TEXT DEFAULT '',
    metadata       TEXT DEFAULT '{}',
    threat_desc    TEXT DEFAULT '',
    acknowledged   BOOLEAN NOT NULL DEFAULT FALSE,
    ack_reason     TEXT DEFAULT ''
);

-- Copy the columns present on BOTH the fresh (19-col) and legacy paths. threat_desc
-- is intentionally NOT referenced in the SELECT because it is absent on a fresh
-- migrated DB (would be "no such column"); it defaults to '' in the new table.
INSERT INTO events (
    event_id, timestamp, event_type, source_hash, source_ip, server_ip, domain,
    query_type, resolved_ip, blocked, anomaly_score, tags, geo, device_vendor,
    network_segment, dns_source, metadata, acknowledged, ack_reason
)
SELECT
    event_id, timestamp, event_type, source_hash, source_ip, server_ip, domain,
    query_type, resolved_ip, blocked, anomaly_score, tags, geo, device_vendor,
    network_segment, dns_source, metadata, acknowledged, ack_reason
FROM events_old_019;

DROP TABLE events_old_019;

CREATE INDEX IF NOT EXISTS idx_events_timestamp    ON events (timestamp);
CREATE INDEX IF NOT EXISTS idx_events_type         ON events (event_type);
CREATE INDEX IF NOT EXISTS idx_events_source       ON events (source_hash);
CREATE INDEX IF NOT EXISTS idx_events_anomaly      ON events (anomaly_score);
CREATE INDEX IF NOT EXISTS idx_events_domain       ON events (domain);
CREATE INDEX IF NOT EXISTS idx_events_type_time    ON events (event_type, timestamp);
CREATE INDEX IF NOT EXISTS idx_events_source_ip    ON events (source_ip);
CREATE INDEX IF NOT EXISTS idx_events_ack          ON events (acknowledged);

-- ── devices ───────────────────────────────────────────────────────────────────
ALTER TABLE devices RENAME TO devices_old_019;

CREATE TABLE devices (
    device_id    TEXT PRIMARY KEY,
    first_seen   TIMESTAMP NOT NULL,
    last_seen    TIMESTAMP NOT NULL,
    ip_address   TEXT NOT NULL,
    mac_address  TEXT NOT NULL,
    hostname     TEXT,
    vendor       TEXT,
    open_ports   TEXT DEFAULT '[]',
    segment      TEXT DEFAULT 'default',   -- segment CHECK dropped (VED-013)
    device_type  TEXT DEFAULT '',
    os_family    TEXT DEFAULT '',
    os_version   TEXT DEFAULT '',
    model        TEXT DEFAULT '',
    discovery_method TEXT DEFAULT 'nmap_active',
    fingerprint_confidence REAL DEFAULT 0.0,
    custom_name  TEXT DEFAULT '',
    notes        TEXT DEFAULT '',
    eol_risk     INTEGER DEFAULT 0,
    eol_model    TEXT DEFAULT '',
    risk_category TEXT DEFAULT '',
    risk_model    TEXT DEFAULT '',
    risk_reasons  TEXT DEFAULT '',
    display_name  TEXT DEFAULT '',
    friendly_name TEXT DEFAULT '',
    services      TEXT DEFAULT '[]'
);

-- 'services' is intentionally NOT referenced in the SELECT: on a fresh migrated
-- DB it is added by the db.go runtime ensure AFTER migrations run, so it does not
-- yet exist at migration time (would be "no such column"). It is declared in the
-- new table above and defaults to '[]'; the post-migration ensure then sees it
-- present and is a no-op. On a legacy DB any prior services JSON is regenerated on
-- the next device upsert.
INSERT INTO devices (
    device_id, first_seen, last_seen, ip_address, mac_address, hostname, vendor,
    open_ports, segment, device_type, os_family, os_version, model,
    discovery_method, fingerprint_confidence, custom_name, notes, eol_risk,
    eol_model, risk_category, risk_model, risk_reasons, display_name,
    friendly_name
)
SELECT
    device_id, first_seen, last_seen, ip_address, mac_address, hostname, vendor,
    open_ports, segment, device_type, os_family, os_version, model,
    discovery_method, fingerprint_confidence, custom_name, notes, eol_risk,
    eol_model, risk_category, risk_model, risk_reasons, display_name,
    friendly_name
FROM devices_old_019;

DROP TABLE devices_old_019;

CREATE INDEX IF NOT EXISTS idx_devices_mac        ON devices (mac_address);
CREATE INDEX IF NOT EXISTS idx_devices_last       ON devices (last_seen);
CREATE INDEX IF NOT EXISTS idx_devices_ip_segment ON devices (ip_address, segment);

PRAGMA foreign_keys = ON;
